package codexprofile

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	ProfileName     = "pika-go-managed"
	OwnershipMarker = "# Managed by pika-go; do not edit this file directly."
)

type Options struct {
	CodexHome       string
	InstanceBin     string
	PikaExecutable  string
	CodexExecutable string
}

type snapshot struct {
	path    string
	existed bool
	content []byte
	mode    os.FileMode
}

// Install writes the single global Pika-owned Codex overlay and an instance-local
// codex launcher. The returned function restores exactly the prior files.
func Install(options Options) (func() error, error) {
	if err := validateOptions(options); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(options.CodexHome, 0o700); err != nil {
		return nil, fmt.Errorf("create Codex config directory: %w", err)
	}
	if err := os.MkdirAll(options.InstanceBin, 0o700); err != nil {
		return nil, fmt.Errorf("create instance binary directory: %w", err)
	}
	profilePath := filepath.Join(options.CodexHome, ProfileName+".config.toml")
	wrapperPath := filepath.Join(options.InstanceBin, "codex")
	profileBefore, err := inspect(profilePath)
	if err != nil {
		return nil, err
	}
	if profileBefore.existed && !strings.HasPrefix(string(profileBefore.content), OwnershipMarker+"\n") {
		return nil, fmt.Errorf("reserved Codex profile %s is not owned by pika-go", profilePath)
	}
	wrapperBefore, err := inspect(wrapperPath)
	if err != nil {
		return nil, err
	}

	if err := writeAtomic(profilePath, []byte(renderProfile(options.PikaExecutable)), 0o600); err != nil {
		return nil, err
	}
	if err := writeAtomic(wrapperPath, []byte(renderWrapper(options.CodexExecutable)), 0o700); err != nil {
		_ = restore(profileBefore)
		return nil, err
	}
	return func() error {
		var restoreErrors []error
		for _, before := range []snapshot{wrapperBefore, profileBefore} {
			if err := restore(before); err != nil {
				restoreErrors = append(restoreErrors, err)
			}
		}
		return errors.Join(restoreErrors...)
	}, nil
}

func validateOptions(options Options) error {
	for label, path := range map[string]string{
		"Codex config directory":    options.CodexHome,
		"instance binary directory": options.InstanceBin,
		"pika-go executable":        options.PikaExecutable,
		"Codex executable":          options.CodexExecutable,
	} {
		if path == "" || !filepath.IsAbs(path) {
			return fmt.Errorf("%s must be an absolute path", label)
		}
	}
	for label, path := range map[string]string{"pika-go executable": options.PikaExecutable, "Codex executable": options.CodexExecutable} {
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("inspect %s: %w", label, err)
		}
		if info.IsDir() || info.Mode().Perm()&0o111 == 0 {
			return fmt.Errorf("%s is not executable: %s", label, path)
		}
	}
	return nil
}

func renderProfile(pikaExecutable string) string {
	hookCommand := shellQuote(pikaExecutable) + " hook codex"
	var builder strings.Builder
	builder.WriteString(OwnershipMarker + "\n")
	builder.WriteString("# This is a named overlay. The base Codex configuration and hooks remain active.\n\n")
	builder.WriteString("[features]\nhooks = true\n\n")
	builder.WriteString("[mcp_servers.pika_go]\n")
	builder.WriteString("command = " + strconv.Quote(pikaExecutable) + "\n")
	builder.WriteString("args = [\"mcp-proxy\"]\n")
	builder.WriteString("env_vars = [\"PIKA_GO_SOCKET\", \"PIKA_MCP_GRANT\"]\n")
	builder.WriteString("default_tools_approval_mode = \"approve\"\n")
	builder.WriteString("startup_timeout_sec = 5\n")
	builder.WriteString("tool_timeout_sec = 3600\n")
	for _, event := range []string{"SessionStart", "SessionEnd", "UserPromptSubmit", "PostToolUse", "Stop"} {
		builder.WriteString("\n[[hooks." + event + "]]\n")
		builder.WriteString("\n[[hooks." + event + ".hooks]]\n")
		builder.WriteString("type = \"command\"\n")
		builder.WriteString("command = " + strconv.Quote(hookCommand) + "\n")
		builder.WriteString("timeout = 3\n")
	}
	return builder.String()
}

func renderWrapper(codexExecutable string) string {
	return "#!/bin/sh\n" +
		"# Managed by pika-go for this instance.\n" +
		"export HERDR_AGENT=codex\n" +
		"if [ -n \"${PIKA_CODEX_DEVELOPER_INSTRUCTIONS_TOML:-}\" ]; then\n" +
		"  set -- -c \"developer_instructions=${PIKA_CODEX_DEVELOPER_INSTRUCTIONS_TOML}\" \"$@\"\n" +
		"fi\n" +
		"if [ -n \"${PIKA_AGENT_REASONING_EFFORT:-}\" ]; then\n" +
		"  set -- -c \"model_reasoning_effort=\\\"${PIKA_AGENT_REASONING_EFFORT}\\\"\" \"$@\"\n" +
		"fi\n" +
		"if [ -n \"${PIKA_AGENT_MODEL:-}\" ]; then\n" +
		"  set -- --model \"${PIKA_AGENT_MODEL}\" \"$@\"\n" +
		"fi\n" +
		"if [ \"${PIKA_CODEX_BYPASS_HOOK_TRUST:-}\" = 1 ]; then\n" +
		"  set -- --dangerously-bypass-hook-trust \"$@\"\n" +
		"fi\n" +
		"set -- --ask-for-approval never \"$@\"\n" +
		"set -- --profile " + ProfileName + " \"$@\"\n" +
		"exec " + shellQuote(codexExecutable) + " \"$@\"\n"
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func inspect(path string) (snapshot, error) {
	result := snapshot{path: path}
	info, err := os.Stat(path)
	if errors.Is(err, os.ErrNotExist) {
		return result, nil
	}
	if err != nil {
		return snapshot{}, fmt.Errorf("inspect managed file %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return snapshot{}, fmt.Errorf("managed path is not a regular file: %s", path)
	}
	contents, err := os.ReadFile(path)
	if err != nil {
		return snapshot{}, fmt.Errorf("read managed file %s: %w", path, err)
	}
	result.existed = true
	result.content = contents
	result.mode = info.Mode().Perm()
	return result, nil
}

func restore(before snapshot) error {
	if before.existed {
		return writeAtomic(before.path, before.content, before.mode)
	}
	if err := os.Remove(before.path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove newly installed file %s: %w", before.path, err)
	}
	return nil
}

func writeAtomic(path string, content []byte, mode os.FileMode) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".pika-go-managed-*.tmp")
	if err != nil {
		return fmt.Errorf("create temporary managed file: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryPath)
	}()
	if err := temporary.Chmod(mode); err != nil {
		return fmt.Errorf("set managed file mode: %w", err)
	}
	if _, err := temporary.Write(content); err != nil {
		return fmt.Errorf("write managed file: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		return fmt.Errorf("sync managed file: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close managed file: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("commit managed file %s: %w", path, err)
	}
	return nil
}
